### ISSUE TITLE
Modeline underlined

### ISSUE THREAD

**Issue by bricewge** [bbatsov/solarized-emacs#113]
With GNU Emacs 24.3.1 I have the modeline broken with an underline.

![emacs](https://cloud.githubusercontent.com/assets/5525646/2748047/50c4ff3c-c7a2-11e3-9c6e-51c84faf769e.png)

It look like the issue #101.

**Comment by idanko** [comment]
This theme can be fixed as:
```elisp
  (custom-set-faces
   '(mode-line ((t (:underline nil))))
   '(mode-line-inactive ((t (:underline nil))))))

```
