### ISSUE TITLE
Shell buffer with mostly unreadable output

### ISSUE THREAD

**Issue by ghost** [bbatsov/solarized-emacs#120]
Opening a shell buffer gives me this reasonably unreadable output on 20140408.1309...
Dark version is even worse.
![emacsshell](https://cloud.githubusercontent.com/assets/1409049/3280893/e5bbba8c-f483-11e3-8cba-ad1585d02e0d.png)

**Comment by thomasf** [comment]
Closing because old and could not reproduce..
