### ISSUE TITLE
Specifying properties for pos-tip

### ISSUE THREAD

**Issue by grettke** [bbatsov/solarized-emacs#122]
Good evening,

Tonight I was trying to figure out how to update [solarized-emacs](https://github.com/bbatsov/solarized-emacs) to provide
[pos-tip](https://github.com/pitkali/pos-tip) with the face values for `pos-tip-foreground-color` and
 `pos-tip-background-color` with faces and themes. For that matter, I couldn't
even do it right for pos-tip eg:

    (setq pos-tip-foreground-color '("red" "blue"))
    (setq pos-tip-background-color '("red" "blue"))
    (pos-tip-show "ALERT")
    ;; NO
    (setq pos-tip-foreground-color (list "red" "blue"))
    (setq pos-tip-background-color (list "red" "blue"))
    (pos-tip-show "ALERT")
    ;; NO
    (setq pos-tip-foreground-color (cons "red" "blue"))
    (setq pos-tip-background-color (cons "red" "blue"))
    (pos-tip-show "ALERT")
    ;; NO
    (setq pos-tip-foreground-color "red")
    (setq pos-tip-background-color "blue")
    (pos-tip-show "ALERT")
    ;; YES
    (setq pos-tip-foreground-color '((:foreground "blue")(:background "red")))
    (setq pos-tip-background-color '((:foreground "blue")(:background "red")))
    (pos-tip-show "ALERT")
    ;; NO
    (setq pos-tip-foreground-color '((:foreground "blue")))
    (setq pos-tip-background-color '((:background "red")))
    (pos-tip-show "ALERT")
    ;; NO

Why am I even writing this? Because if pos-tip could get its color info from this
theme then it would rock. pos-tip is really nice, and if it is installed then
[auto-complete](http://melpa.milkbox.net/#/auto-complete) uses it, and you already set properties for that in your theme.

Where might I focus next to investigate/debug this further?

Kind regards,

gcr

**Comment by expez** [comment]
ping @grettke

**Comment by grettke** [comment]
Hi @expez what is up?

**Comment by grettke** [comment]
@thomasf I added it and it didn't work. Perhaps I didn't recompile correctly. If you are up for it that would be super, please do.

**Comment by thomasf** [comment]
I can do it within a few days, ping back if I haven't done so..

**Comment by grettke** [comment]
Thank you, will do.

**Comment by grettke** [comment]
@thomasf Pinging you as I don't see it in there.

**Comment by expez** [comment]
@thomasf  I've vendored `pos-tip` and edited a few lines, until this is resolved:

```elisp
(defvar pos-tip-foreground-color "#839496"
  "Default foreground color of pos-tip's tooltip.")

(defvar pos-tip-background-color "#073642"
  "Default background color of pos-tip's tooltip.")
```

I think this looks pretty good, and would prefer this to the yellow alternative suggested earlier.

![Imgur](http://i.imgur.com/N1MUzU5.png)

**Comment by expez** [comment]
@thomasf ping!

**Comment by thomasf** [comment]
Sorry., commit is coming right away..

**Comment by thomasf** [comment]
done in https://github.com/bbatsov/solarized-emacs/commit/3efc1ec8a1338570613726975098a261c3921b7d

**Comment by grettke** [comment]
@thomasf Thank you sir.
