### ISSUE TITLE
Error when loading solarized theme

### ISSUE THREAD

**Issue by alexmurray** [bbatsov/solarized-emacs#140]
I am using emacs-snapshot from https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa

    emacs --version
    GNU Emacs 25.0.50.1
    Copyright (C) 2014 Free Software Foundation, Inc.
    GNU Emacs comes with ABSOLUTELY NO WARRANTY.
    You may redistribute copies of Emacs
    under the terms of the GNU General Public License.
    For more information about these matters, see the file named COPYING.

And I get the following failure which I think is as a result of the recent changes in https://github.com/bbatsov/solarized-emacs/commit/1c5d7fb0fe95e96994ecb6dabf80dc00154b02ef

    Debugger entered--Lisp error: (void-function \,)
    (\, solarized-height-plus-4)
    (list :height (\, solarized-height-plus-4))
    (progn (list :height (\, solarized-height-plus-4)))
    (if solarized-scale-org-headlines (progn (list :height (\, solarized-height-plus-4))))
    (cons orange (if solarized-scale-org-headlines (progn (list :height (\, solarized-height-plus-4)))))
    (cons (quote :foreground) (cons orange (if solarized-scale-org-headlines (progn (list :height (\, solarized-height-plus-4))))))
    (cons s-variable-pitch (cons (quote :foreground) (cons orange (if solarized-scale-org-headlines (progn (list :height (\, solarized-height-plus-4)))))))
    (cons (quote :inherit) (cons s-variable-pitch (cons (quote :foreground) (cons orange (if solarized-scale-org-headlines (progn (list :height (\, solarized-height-plus-4))))))))
    (list class (cons (quote :inherit) (cons s-variable-pitch (cons (quote :foreground) (cons orange (if solarized-scale-org-headlines (progn (list :height ...))))))))
    (list (list class (cons (quote :inherit) (cons s-variable-pitch (cons (quote :foreground) (cons orange (if solarized-scale-org-headlines (progn ...))))))))
    (list (quote org-level-1) (list (list class (cons (quote :inherit) (cons s-variable-pitch (cons (quote :foreground) (cons orange (if solarized-scale-org-headlines ...))))))))
    (custom-theme-set-faces theme-name (quote (button ((t (:underline t))))) (list (quote default) (list (list class (list (quote :foreground) base0 (quote :background) base03)))) (list (quote shadow) (list (list class (list (quote :foreground) base01)))) (list (quote match) (list (list class (cons (quote :background) (cons base02 (cons (quote :foreground) (cons base1 ...))))))) (list (quote cursor) (list (list class (cons (quote :foreground) (cons base03 (cons (quote :background) (cons base0 ...))))))) (list (quote mouse) (list (list class (cons (quote :foreground) (cons base03 (cons (quote :background) (cons base0 ...))))))) (list (quote escape-glyph) (list (list class (list (quote :foreground) violet)))) (list (quote fringe) (list (list class (list (quote :foreground) s-fringe-fg (quote :background) s-fringe-bg)))) (list (quote highlight) (list (list class (list (quote :background) base02)))) (list (quote link) (list (list class (cons (quote :foreground) (cons yellow (quote (:underline t :weight bold))))))) (list (quote link-visited) (list (list class (cons (quote :foreground) (cons yellow (quote (:underline t :weight normal))))))) (list (quote success) (list (list class (list (quote :foreground) green)))) (list (quote warning) (list (list class (list (quote :foreground) yellow)))) (list (quote error) (list (list class (list (quote :foreground) orange)))) (list (quote lazy-highlight) (list (list class (cons (quote :foreground) (cons base03 (cons (quote :background) (cons yellow ...))))))) (list (quote compilation-column-face) (list (list class (cons (quote :foreground) (cons cyan (quote (:underline nil))))))) (list (quote compilation-column-number) (list (list class (cons (quote :inherit) (cons (quote font-lock-doc-face) (cons (quote :foreground) (cons cyan ...))))))) (list (quote compilation-enter-directory-face) (list (list class (cons (quote :foreground) (cons green (quote (:underline nil))))))) (list (quote compilation-error) (list (cons class (quote ((:inherit error :underline nil)))))) (list (quote compilation-error-face) (list (list class (cons (quote :foreground) (cons red (quote (: :underline nil))))))) (list (quote compilation-face) (list (list class (cons (quote :foreground) (cons base0 (quote (:underline nil))))))) (list (quote compilation-info) (list (list class (cons (quote :foreground) (cons base01 (quote (:underline nil :bold nil))))))) (list (quote compilation-info-face) (list (list class (cons (quote :foreground) (cons blue (quote (:underline nil))))))) (list (quote compilation-leave-directory-face) (list (list class (cons (quote :foreground) (cons green (quote (:underline nil))))))) (list (quote compilation-line-face) (list (list class (cons (quote :foreground) (cons green (quote (:underline nil))))))) (list (quote compilation-line-number) (list (list class (cons (quote :foreground) (cons green (quote (:underline nil))))))) (list (quote compilation-warning) (list (cons class (quote ((:inherit warning :underline nil)))))) (list (quote compilation-warning-face) (list (list class (cons (quote :foreground) (cons yellow (quote (:weight normal :underline nil))))))) (list (quote compilation-mode-line-exit) (list (list class (cons (quote :inherit) (cons (quote compilation-info) (cons (quote :foreground) (cons green ...))))))) (list (quote compilation-mode-line-fail) (list (list class (cons (quote :inherit) (cons (quote compilation-error) (cons (quote :foreground) (cons red ...))))))) (list (quote compilation-mode-line-run) (list (list class (cons (quote :foreground) (cons orange (quote (:weight bold))))))) (list (quote cua-global-mark) (list (list class (list (quote :background) yellow (quote :foreground) base03)))) (list (quote cua-rectangle) (list (list class (list (quote :inherit) (quote region) (quote :background) magenta (quote :foreground) base03)))) (list (quote cua-rectangle-noselect) (list (list class (list (quote :inherit) (quote region) (quote :background) base02 (quote :foreground) base01)))) (list (quote diary) (list (list class (list (quote :foreground) yellow)))) (list (quote dired-directory) (list (list class (cons (quote :foreground) (cons blue (quote (:weight normal))))))) (list (quote dired-flagged) (list (list class (list (quote :foreground) red)))) (list (quote dired-header) (list (list class (list (quote :foreground) base03 (quote :background) blue)))) (list (quote dired-ignored) (list (cons class (quote ((:inherit shadow)))))) (list (quote dired-mark) (list (list class (cons (quote :foreground) (cons yellow (quote (:weight bold))))))) (list (quote dired-marked) (list (list class (cons (quote :foreground) (cons magenta (quote (:weight bold))))))) (list (quote dired-perm-write) (list (list class (cons (quote :foreground) (cons base0 (quote (:underline t))))))) (list (quote dired-symlink) (list (list class (cons (quote :foreground) (cons cyan (quote (:weight normal :slant italic))))))) (list (quote dired-warning) (list (list class (cons (quote :foreground) (cons orange (quote (:underline t))))))) (list (quote dired-async-message) (list (list class (list (quote :background) (if (eq variant (quote light)) yellow-l yellow))))) (list (quote dired-async-mode-message) (list (list class (list (quote :background) (if (eq variant (quote light)) red-l red))))) (list (quote dired-efap-face) (list (list class (cons (quote :box) (cons nil (cons (quote :background) (cons base02 ...))))))) (list (quote dropdown-list-face) (list (list class (list (quote :background) base02 (quote :foreground) cyan)))) ...)
    (let* ((class (quote ((class color) (min-colors 89)))) (s-base03 "#002b36") (s-base02 "#073642") (s-base01 "#586e75") (s-base00 "#657b83") (s-base0 "#839496") (s-base1 "#93a1a1") (s-base2 "#eee8d5") (s-base3 "#fdf6e3") (yellow "#b58900") (orange "#cb4b16") (red "#dc322f") (magenta "#d33682") (violet "#6c71c4") (blue "#268bd2") (cyan "#2aa198") (green "#859900") (yellow-d "#7B6000") (yellow-l "#DEB542") (orange-d "#8B2C02") (orange-l "#F2804F") (red-d "#990A1B") (red-l "#FF6E64") (magenta-d "#93115C") (magenta-l "#F771AC") (violet-d "#3F4D91") (violet-l "#9EA0E5") (blue-d "#00629D") (blue-l "#69B7F0") (cyan-d "#00736F") (cyan-l "#69CABF") (green-d "#546E00") (green-l "#B4C342") (base0 (if (eq variant (quote light)) s-base00 s-base0)) (base00 (if (eq variant (quote light)) s-base0 s-base00)) (base1 (if (eq variant (quote light)) s-base01 s-base1)) (base01 (if (eq variant (quote light)) s-base1 s-base01)) (base2 (if (eq variant (quote light)) s-base02 s-base2)) (base02 (if (eq variant (quote light)) s-base2 s-base02)) (base3 (if (eq variant (quote light)) s-base03 s-base3)) (base03 (if (eq variant (quote light)) s-base3 s-base03)) (solarized-fg (if (eq variant (quote light)) s-base00 s-base0)) (solarized-bg (if (eq variant (quote light)) s-base3 s-base03)) (solarized-hl (if (eq variant (quote light)) s-base2 s-base02)) (solarized-emph (if (eq variant (quote light)) s-base01 s-base1)) (solarized-comments (if (eq variant (quote light)) s-base1 s-base01)) (solarized-fg-hc (if (eq variant (quote light)) s-base3 s-base03)) (solarized-fg-lc (if (eq variant (quote light)) s-base03 s-base3)) (s-line (if (eq variant (quote light)) "#cccec4" "#284b54")) (yellow-hc (if (eq variant (quote light)) yellow-d yellow-l)) ...) (custom-theme-set-faces theme-name (quote (button ((t (:underline t))))) (list (quote default) (list (list class (list (quote :foreground) base0 (quote :background) base03)))) (list (quote shadow) (list (list class (list (quote :foreground) base01)))) (list (quote match) (list (list class (cons (quote :background) (cons base02 (cons ... ...)))))) (list (quote cursor) (list (list class (cons (quote :foreground) (cons base03 (cons ... ...)))))) (list (quote mouse) (list (list class (cons (quote :foreground) (cons base03 (cons ... ...)))))) (list (quote escape-glyph) (list (list class (list (quote :foreground) violet)))) (list (quote fringe) (list (list class (list (quote :foreground) s-fringe-fg (quote :background) s-fringe-bg)))) (list (quote highlight) (list (list class (list (quote :background) base02)))) (list (quote link) (list (list class (cons (quote :foreground) (cons yellow (quote ...)))))) (list (quote link-visited) (list (list class (cons (quote :foreground) (cons yellow (quote ...)))))) (list (quote success) (list (list class (list (quote :foreground) green)))) (list (quote warning) (list (list class (list (quote :foreground) yellow)))) (list (quote error) (list (list class (list (quote :foreground) orange)))) (list (quote lazy-highlight) (list (list class (cons (quote :foreground) (cons base03 (cons ... ...)))))) (list (quote compilation-column-face) (list (list class (cons (quote :foreground) (cons cyan (quote ...)))))) (list (quote compilation-column-number) (list (list class (cons (quote :inherit) (cons (quote font-lock-doc-face) (cons ... ...)))))) (list (quote compilation-enter-directory-face) (list (list class (cons (quote :foreground) (cons green (quote ...)))))) (list (quote compilation-error) (list (cons class (quote ((:inherit error :underline nil)))))) (list (quote compilation-error-face) (list (list class (cons (quote :foreground) (cons red (quote ...)))))) (list (quote compilation-face) (list (list class (cons (quote :foreground) (cons base0 (quote ...)))))) (list (quote compilation-info) (list (list class (cons (quote :foreground) (cons base01 (quote ...)))))) (list (quote compilation-info-face) (list (list class (cons (quote :foreground) (cons blue (quote ...)))))) (list (quote compilation-leave-directory-face) (list (list class (cons (quote :foreground) (cons green (quote ...)))))) (list (quote compilation-line-face) (list (list class (cons (quote :foreground) (cons green (quote ...)))))) (list (quote compilation-line-number) (list (list class (cons (quote :foreground) (cons green (quote ...)))))) (list (quote compilation-warning) (list (cons class (quote ((:inherit warning :underline nil)))))) (list (quote compilation-warning-face) (list (list class (cons (quote :foreground) (cons yellow (quote ...)))))) (list (quote compilation-mode-line-exit) (list (list class (cons (quote :inherit) (cons (quote compilation-info) (cons ... ...)))))) (list (quote compilation-mode-line-fail) (list (list class (cons (quote :inherit) (cons (quote compilation-error) (cons ... ...)))))) (list (quote compilation-mode-line-run) (list (list class (cons (quote :foreground) (cons orange (quote ...)))))) (list (quote cua-global-mark) (list (list class (list (quote :background) yellow (quote :foreground) base03)))) (list (quote cua-rectangle) (list (list class (list (quote :inherit) (quote region) (quote :background) magenta (quote :foreground) base03)))) (list (quote cua-rectangle-noselect) (list (list class (list (quote :inherit) (quote region) (quote :background) base02 (quote :foreground) base01)))) (list (quote diary) (list (list class (list (quote :foreground) yellow)))) (list (quote dired-directory) (list (list class (cons (quote :foreground) (cons blue (quote ...)))))) (list (quote dired-flagged) (list (list class (list (quote :foreground) red)))) (list (quote dired-header) (list (list class (list (quote :foreground) base03 (quote :background) blue)))) (list (quote dired-ignored) (list (cons class (quote ((:inherit shadow)))))) (list (quote dired-mark) (list (list class (cons (quote :foreground) (cons yellow (quote ...)))))) (list (quote dired-marked) (list (list class (cons (quote :foreground) (cons magenta (quote ...)))))) (list (quote dired-perm-write) (list (list class (cons (quote :foreground) (cons base0 (quote ...)))))) (list (quote dired-symlink) (list (list class (cons (quote :foreground) (cons cyan (quote ...)))))) (list (quote dired-warning) (list (list class (cons (quote :foreground) (cons orange (quote ...)))))) (list (quote dired-async-message) (list (list class (list (quote :background) (if (eq variant ...) yellow-l yellow))))) (list (quote dired-async-mode-message) (list (list class (list (quote :background) (if (eq variant ...) red-l red))))) (list (quote dired-efap-face) (list (list class (cons (quote :box) (cons nil (cons ... ...)))))) (list (quote dropdown-list-face) (list (list class (list (quote :background) base02 (quote :foreground) cyan)))) ...) (custom-theme-set-variables theme-name (list (quote ansi-color-names-vector) (vector base02 red green yellow blue magenta cyan base00)) (quote (compilation-message-face (quote default))) (list (quote cua-normal-cursor-color) base0) (list (quote cua-read-only-cursor-color) green) (list (quote cua-global-mark-cursor-color) cyan) (list (quote cua-overwrite-cursor-color) yellow) (list (quote fci-rule-color) base02) (quote (magit-diff-use-overlays nil)) (list (quote highlight-changes-colors) (list (quote quote) (list magenta violet))) (list (quote highlight-symbol-foreground-color) base1) (list (quote highlight-symbol-colors) (list (quote --map) (cons (quote solarized-color-blend) (cons (quote it) (cons base03 (quote ...)))) (list (quote quote) (list yellow cyan red violet green orange blue)))) (list (quote highlight-tail-colors) (list (quote quote) (list (cons base02 (quote 0)) (cons green-lc (quote 20)) (cons cyan-lc (quote 30)) (cons blue-lc (quote 50)) (cons yellow-lc (quote 60)) (cons orange-lc (quote 70)) (cons magenta-lc (quote 85)) (cons base02 (quote 100))))) (list (quote hl-fg-colors) (list (quote quote) (list base03 base03 base03 base03 base03 base03 base03 base03))) (list (quote hl-bg-colors) (list (quote quote) (list yellow-lc orange-lc red-lc magenta-lc violet-lc blue-lc cyan-lc green-lc))) (list (quote smartrep-mode-line-active-bg) (cons (quote solarized-color-blend) (cons green (cons s-mode-line-bg (quote (0.2)))))) (list (quote term-default-fg-color) base0) (list (quote term-default-bg-color) base03) (list (quote vc-annotate-color-map) (list (quote quote) (list (cons 20 red) (cons 40 (solarized-color-blend yellow red (/ 2.0 4))) (cons 60 (solarized-color-blend yellow red (/ 3.0 4))) (cons 80 yellow) (cons 100 (solarized-color-blend green yellow (/ 2.0 6))) (cons 120 (solarized-color-blend green yellow (/ 3.0 6))) (cons 140 (solarized-color-blend green yellow (/ 4.0 6))) (cons 160 (solarized-color-blend green yellow (/ 5.0 6))) (cons 180 green) (cons 200 (solarized-color-blend cyan green (/ 2.0 6))) (cons 220 (solarized-color-blend cyan green (/ 3.0 6))) (cons 240 (solarized-color-blend cyan green (/ 4.0 6))) (cons 260 (solarized-color-blend cyan green (/ 5.0 6))) (cons 280 cyan) (cons 300 (solarized-color-blend blue cyan (/ 2.0 5))) (cons 320 (solarized-color-blend blue cyan (/ 3.0 5))) (cons 340 (solarized-color-blend blue cyan (/ 4.0 5))) (cons 360 blue)))) (quote (vc-annotate-very-old-color nil)) (quote (vc-annotate-background nil)) (list (quote weechat-color-list) (list (quote quote) (list (quote unspecified) base03 base02 red-d red green-d green yellow-d yellow blue-d blue magenta-d magenta cyan-d cyan base0 base00)))) (list (quote xterm-color-names) (vector base02 red green yellow blue magenta cyan base2)) (list (quote xterm-color-names-bright) (vector base03 orange base01 base00 base0 violet base1 base3)) (if childtheme (progn (funcall childtheme))))
    create-solarized-theme(light solarized-light)
    eval-buffer()  ; Reading at buffer position 149
    load-theme(solarized-light t)

**Comment by bbatsov** [comment]
#141 is now merged.

**Comment by henrythebuilder** [comment]
Thanks
 :+1:
