### ISSUE TITLE
fic-mode customization is broken

### ISSUE THREAD

**Issue by expez** [bbatsov/solarized-emacs#151]
This snippet from `solarized-emacs` doesn't really do what it should:

``` elisp
;;;;; fic
     `(fic-author-face ((,class (:background ,base03 :foreground ,orange
                                             :underline t :slant italic))))
     `(fic-face ((,class (:background ,base03 :foreground ,orange
                                      :weight normal :slant italic))))
     `(font-lock-fic-face ((,class (:background ,base03 :foreground ,orange
                                      :weight normal :slant italic)))
```

I can't find any reference to `fic-author-face` or `fic-face` in the source file.  `font-lock-fic-face` is built here:

``` elisp
(make-face 'font-lock-fic-face)
(modify-face 'font-lock-fic-face fic-foreground-color
             fic-background-color nil t nil t nil nil)
```

So what we really want to do is to just set `fic-background-color` and `fic-foreground-color`.

**Comment by thomasf** [comment]
iirc there are two different forks of fic-mode.. I do not have time to check that now.

**Comment by thomasf** [comment]
I've researched this a bit now...

This is fic-ext-mode (from marmalade):

```
(defface font-lock-fic-face
  '((((class color))
     (:background "white" :foreground "red" :weight bold))
    (t (:weight bold)))
  "Face to fontify FIXME/TODO words"
  :group 'fic-ext-mode)

(defconst font-lock-fic-author-face 'font-lock-fic-author-face
  "Face to fontify author/assignee of FIXME/TODO")

(defface font-lock-fic-author-face
  '((((class color))
     (:background "white" :foreground "orangered" :underline t))
    (t (:underline t)))
  "Face to fontify author/assignee of FIXME/TODO"
  :group 'fic-ext-mode)
```

This version at least defines proper faces, and not the ones that this theme defines since the font-lock prefix is missing..

**Comment by expez** [comment]
so if I just switch to that one all is good?

The naming is a bit unfortunate, it's really more like an alternate implementation than an extension :/

Thanks!

**Comment by thomasf** [comment]
I know. That would be a part of fixing this.. Iirc, at one point they were both named fic-mode but thats not the case anymore.
