### ISSUE TITLE
tooltip face

### ISSUE THREAD

**Issue by expez** [bbatsov/solarized-emacs#152]
`tooltip.el` has a face (simply named `tooltip`)which is unbound.  Might I suggest it is bound to the same colors as for [pos-tip](https://github.com/bbatsov/solarized-emacs/issues/122).

Note, on linux I only saw the `tooltip` face after setting `x-gtk-use-system-tooltips` to `nil`.  Not sure how to change the color when that variable is `t`, or if emac's own tooltips are better or worse than the gtk alternative.

**Comment by wasamasa** [comment]
See also https://github.com/pitkali/pos-tip/pull/7 for a pull request of mine that would support setting up a tooltip face instead of pos-tip colors.
