### ISSUE TITLE
Consider using less similar faces for font-lock-doc-face and font-lock-string-face

### ISSUE THREAD

**Issue by cichli** [bbatsov/solarized-emacs#158]
Currently they are defined as:

```emacs-lisp
`(font-lock-doc-face ((,class (:foreground ,cyan :slant ,s-maybe-italic))))
```

```emacs-lisp
`(font-lock-string-face ((,class (:foreground ,cyan))))
```

Which only differ by the former being italic when `solarized-use-more-italic` is non-nil.

Perhaps using a different colour (a la zenburn) would be better:

<img src="https://www.dropbox.com/s/r45t2i825wbdgm4/Screenshot%202015-02-22%2019.10.02.png?raw=1" width="500" />

vs.

<img src="https://cloud.githubusercontent.com/assets/103882/6318908/1ddcb4cc-bab1-11e4-8d37-95e8905bc627.png" width="500" />

**Comment by thomasf** [comment]
I would probably vote no because of increased color pasta.. 
Zenburn has a more suited palette for these kinds of things, more colors and softer contrast.

**Comment by oscarfv** [comment]
Thomas Frössman <notifications@github.com> writes:

> I would probably vote no because of increased color pasta.. 

+1

**Comment by bbatsov** [comment]
I'm in favour of changing this - I'm pretty sure I didn't originally use the same colours; I just missed when this happened. The especially troubling bit is the by default the faces don't differ at all and `maybe-italic` has to set before loading the theme (something which many users fail to realise).

**Comment by thomasf** [comment]
Yeah, iirc I changed that and some other things to reduce information in favor of a more pleasant reading experience.

**Comment by thomasf** [comment]
So..  
How bad do you want this? 
If the answer is very much so I suggest that we  add a new defcustom while keeping the current look default.

**Comment by bbatsov** [comment]
> Yeah, iirc I changed that and some other things to reduce information in favor of a more pleasant reading experience. In this instance and languages I can think of docstrings are easily found by following a function definition so it does not necessarily warrant adding more colors to the display.

It's pretty debatable if this current setup provides "a more pleasant reading experience". At any rate - in languages like Clojure the inability to differentiate between the two actually causes real issues, as programmers often misplace the docstrings but can't actually see this. @cichli's example illustrates just this. In zenburn it's crystal clear there's a problem, but in solarized you'll be hard pressed to notice the problem. I've always been against using the same faces for different syntactic groups.

**Comment by thomasf** [comment]
I see!

First, I think that it works better having more colors at once in zenburn than
in solarized because of which colors are available and how they relate to each
other.

Two possible options (which I have not tested) that comes to mind:

1. Use the normal foreground color.

It clearly separates normal strings from doc strings.
I'm not aware of any particular problems that would arise from it. 

2. Use the comment foreground color.

It clearly separates normal strings from doc strings. Documentation would have
the same color for languages that has doc strings and those that just uses
plain comments for generating documentation. I guess that this could create a
situation similar to the current one if there are modes that adds doc face
formatting inside comments.

**Comment by thomasf** [comment]
@bbatsov Yes, everything is always debatable :) 

Being very restrictive with color assignment has proven to be a good default
for several reasons.

I like to be able to have a strong motivation for these things and now that you
explained possible practical problems it's another ball game (for me).

**Comment by bbatsov** [comment]
> Seems a bit strange to me that people often would make this mistake. The incorrectly placed [handler] is very easy to spot just, I guess it could be less so in other situations than in the picture.

The problem is that in many Lisps the docstring follows the params and you won't actually get an error or warning if you make this mistake. :-)

I'm fine with using the normal or the comment face. Your call.

**Comment by thomasf** [comment]
I quickly checked the major modes for python/clojure/haskell/js/go and elisp.

There were a range problems caused differences in language syntax, docstring syntax and major mode implementation details.. I'll have to get back to this later.

**Comment by thomasf** [comment]
The best thing about using the string face is that strings and docstrings very seldom appear in direct contact.. For many other colors there are situations like these:

Too much contrast shifting w. comment style:
![image](https://cloud.githubusercontent.com/assets/330847/7003343/16bd4a66-dc59-11e4-8be1-dae3ae4a09fe.png)

The line after the doc string continues with the same color:
![image](https://cloud.githubusercontent.com/assets/330847/7003359/829c28ce-dc59-11e4-847d-04929989778c.png)

Now it's hard to find function definitions
![image](https://cloud.githubusercontent.com/assets/330847/7003366/9a5da898-dc59-11e4-884e-1d01ed8be78a.png)

Here the docstrings and regular code collide:
![image](https://cloud.githubusercontent.com/assets/330847/7003422/8fa2259a-dc5a-11e4-8e75-2d658f6bb9dd.png)

**Comment by thomasf** [comment]
Violet is the least used color which I haven't assigned a strong  semantic meaning for.. A defcustom to enable docstrings to be in violet is maybe a solution..

**Comment by thomasf** [comment]
the `use-more-italics` defcustom was introduced because some fonts have lousy suoport for italics. Italics should really be enough. In respect to the kind of isses pictured in the screenshot above I now propuse a new defcstom that enables this:

![image](https://cloud.githubusercontent.com/assets/330847/7029554/b533ba9e-dd5e-11e4-9b5f-95030cd73502.png)

**Comment by cichli** [comment]
Sorry - been meaning to get back to you on this. I've been using the italic setting since I logged this issue and I'm pretty used to it now, but I think I'd prefer the violet + no italic (like you say italic doesn't look great in some fonts). So an option for that would be most welcome :-).

**Comment by thomasf** [comment]
Thanks for your input.

I'll add a customization option to enable violet look.

Also note that currently, the faces `font-lock-function-name-face`, `font-lock-variable-name-face` and `font-lock-preprocessor-face` are totally identical using only plain blue. In the end it's about balance and making good use of the very few colors we have available.
