### ISSUE TITLE
Fix smart-mode-line display

### ISSUE THREAD

**Issue by thomasf** [bbatsov/solarized-emacs#163]
Current issues:

* Too many colors are used in vain.
* All faces shoud maybe be defined, depends on how this issue is resolved.
* Current defs are not compatible with solarized-high-contrast-mode-line, this is maybe not a strict requirement but might be doable without too much effort.

**Comment by thomasf** [comment]
My initial thoughts are leaning towards only letting `sml/outside-modified` and `sml/sudo` stand out from everything else since those can produce the most severe side effects is missed and would not be lit most of the time during normal usage anyway.

**Comment by thomasf** [comment]
There is also the issue of inactive/active mode-line facedefs not being used unless not specifying colors at all. 
@andschwa  Maybe this theme could require a an optional defcustom and  default to be turned off?  I don't feel all these colors match well to general feel of this theme..

**Comment by thomasf** [comment]
I just tinkered  a bit and this might be my suggestion for a default set of colors:

```elisp
     ;; just stand out slightly more on inactive mode lines
     `(sml/filename ((,class (:foreground ,base1 :weight bold))))
     `(sml/prefix ((,class (:foreground ,base0))))
     ;; warning
     `(sml/sudo ((,class (:foreground ,orange :weight bold))))
     ;; indication of change
     `(sml/modified ((,class (:foreground ,yellow))))
     `(sml/vc-edited ((,class (:foreground ,yellow))))
     `(sml/outside-modified ((,class (:foreground ,yellow))))
```

**Comment by andschwa** [comment]
Woops, sorry for not noticing this issue sooner, for some reason I wasn't watching the repo! I've let the colors sink in myself for a while now and definitely feel they can be improved. Thanks for writing up the color usage guideline by the way in #162.

My initial thoughts on things that *should* have colors:

* Running processes should remain magenta, as they are a temporary thing which needs to be highlighted
* Read-only and sudo should have colors as their indicators are *small*
* Charging/discharging should be either green/red or green/orange
* `outside-modified` should be a different color, as it conveys totally different, but important, information from modified internally

I'm testing out yours with the addition of
```
     `(sml/git ((,class (:foreground ,base0))))
```
So that a prefix even in a Git repo remains the same color.

I would *like* to highlight `sml/vc` as the current branch/tag in a repo is probably the most important information in the modeline. It's yellow right now, which means that the modified color isn't actually a change. Perhaps blue for unmodified and yellow for modified and vc-edited?

**Comment by thomasf** [comment]
I'll keep writing in this issue thread for now.. 

Some thoughts:

**The mode line as divider **

I think the main reason for me being against using more than a few colors in total is that the feeling of the mode line being a divider with a certain look is lessened.

**specifying foreground colors breaks active/inactive modeline**

 All use of :foreground inhibits the default active/inactive mode line colors. Everything that does not use a accent color should probably not use :foreground at all.

**Charging/discharging:**

 I do not use that so I did not update the faces..  I would not use colors at all because the information is always present at exactly the same place and know where to look for it and if my computer is running on battery or not,. If it were possible to set red for 10% bettery left or something that would be another thing..  Green/orange is probably fine.

**Comment by thomasf** [comment]
This color was added more or less specifically for the intent of having the mode line look just a bit better:

```elisp
        ;; NOTE only use this for very thin lines that are hard to see using base02, in low
         ;; color displayes base02 might be used instead
         (s-line (if (eq variant 'light) "#cccec4" "#284b54"))
```

**Comment by andschwa** [comment]
I'm not sure what you mean by foreground breaking the active/inactive mode-line colors. It's the *background* color that dominates the mode-line's function as separator, and that changes just fine. (In addition, we have the line you just pointed out.)

**Comment by thomasf** [comment]
The bg/fg combo switches between base02/base0 and base01/base03 for the active/inactive  states.

**Comment by andschwa** [comment]
We could certainly easily use those; is it to achieve more of a dimming effect?

**Comment by thomasf** [comment]
Yes, that's the reason.. A dimmed inactive mode line.

**Comment by thomasf** [comment]
I might have misunderstood sml but at least in the past it did not support the notion of active/inactive mode lines.

**Comment by andschwa** [comment]
I'm looking at it right now trying to figure that out. It doesn't seem to support it. In which case, does `:foreground` have any detrimental effect on sml?

**Comment by thomasf** [comment]
In the end it's all a matter of taste anyway. I would really like to modularize this theme to allow easier composition of things.. But it's such an large task because it requires retesting/verifying hundreds (?) of modes in the process.

**Comment by thomasf** [comment]
I think this might be a good minimalistic theme.
```
   `(sml/filename ((,class (:foreground ,base1 :weight bold))))
     `(sml/prefix ((,class (:foreground unspecified))))
     `(sml/git ((,class (:foreground unspecified))))
     `(sml/process ((,class (:weight bold))))
     `(sml/sudo ((,class  (:foreground ,orange :weight bold))))
     `(sml/read-only ((,class (:foreground ,cyan))))
     `(sml/outside-modified ((,class (:foreground ,cyan :weight bold))))
     `(sml/modified ((,class (:foreground ,cyan))))
     `(sml/vc-edited ((,class (:foreground ,green))))
     `(sml/charging            ((,class (:foreground ,base1))))
     `(sml/discharging         ((,class (:foreground ,base1 :weight bold))))
```
![image](https://cloud.githubusercontent.com/assets/330847/6725969/48c671c8-ce11-11e4-9ae0-54169295a2fd.png)

**Comment by thomasf** [comment]
I commited almost whats pictured above for now.. Further discussion can continue in the related pull request
