### ISSUE TITLE
Solarized dark theme now light after upgrade on MELPA

### ISSUE THREAD

**Issue by bgvianyc** [bbatsov/solarized-emacs#167]
I just updated my packages via MELPA. Now my solarized dark theme is light despite no changes to init.el. 

Seems like a bug.

**Comment by thomasf** [comment]
Hmm, works for me.. Cannot see any recent change that would affect something like that.

**Comment by thomasf** [comment]
I'll close this, feel free to reopen and provide additional information if this has not been resolved.
