### ISSUE TITLE
Erlang: Function named "get" misinterpreted as built-in

### ISSUE THREAD

**Issue by luisgerhorst** [bbatsov/solarized-emacs#172]
I'm not sure if this is the right place to complain but I have an Erlang module that defines a function named `get`. As you can see in the screenshot the function is misinterpreted as a build-in Erlang function (like `spawn`, `length` etc.).

![erlang-get](https://cloud.githubusercontent.com/assets/1497741/6886136/34e0bcb0-d634-11e4-9ded-3383c6a2678c.png)

**Comment by bbatsov** [comment]
You should complain on erlang-mode's issue tracker.
