### ISSUE TITLE
new org-mode headlines do not always start on a new 

### ISSUE THREAD

**Issue by dowcet** [bbatsov/solarized-emacs#176]
Since I switched to using this theme, I've noticed that when I add a new heading in org-mode, it sometimes isn't starting on a new line. In other words, if I am at the end of the line on a folded subtree (`** existing heading...`) and I press <kbd>Alt</kbd>+<kbd>Enter</kbd>, then the result may be `** existing line...** ` instead of:

`** existing line...`

`** new line`

This doesn't happen all the time and I cannot reproduce it on demand, so it may be unrelated. But I have no clue what else might be causing it and I wonder what you think.

**Comment by thomasf** [comment]
Hmm, hard to telll.. I've seen this too but it should not have anything todo with the emacs theme system.. Do you also install org-mode from a package, it's more probable that the cause is in there.

**Comment by thomasf** [comment]
I  run emacs directly from the emacs-24 branch so tracking these kinds of things are something I generally won't do because I have to install old/stable versions of things and such... And org-mode is not the easiest thing to debug because of it's hugeness..

**Comment by dowcet** [comment]
> Do you also install org-mode from a package

I do. I'll look into it some more and close this for now.
