### ISSUE TITLE
Removing child-theme support

### ISSUE THREAD

**Issue by xgarrido** [bbatsov/solarized-emacs#177]
dbbade9 commit removes support for child-theme arguing that it has not worked for a long time. I am a bit suprised since I was using this functionality since the beginning and it was working pretty well (see https://github.com/xgarrido/emacs-starter-kit/blob/master/starter-kit-window.org#custom-solarized-theme) 

How to get such feature back and how can I benefit from solarized colors outside of solarized theme ?

**Comment by bbatsov** [comment]
You can simply require solarized and use its colour definitions (or override them). This feature was never used that much, so I view its removal as a good decision.

**Comment by xgarrido** [comment]
This is where I shamefully fail. I am not a lisp coder and basically I am copying/pasting code from other, so forgive my ignorance. Consider the following piece of code

``` lisp
(require 'solarized)
(deftheme sk-solarized "A slightly modified version of solarized theme.")
(defun sk-solarized-theme()
  (custom-theme-set-faces
     'sk-solarized
     `(default ((:background ,blue-d :foreground ,blue-d)))
     ))
```

```blue-d``` symbol variable is void. From what I have read, I thought that all the colors in solarized where ```let``` binded which avoid there use from outside.

**Comment by thomasf** [comment]
@xgarrido Oh, this stopped working for me around one of the 24.4.x releses a very long time ago, maybe it started working again then.

**Comment by thomasf** [comment]
@bbatov as @xgarrido points out the color defs are only available let bound inside the function which creates the theme. Also the inverted based on light/dark theme will not be directly available outside that let scope.

**Comment by thomasf** [comment]
I'll put the old stuff back if it still works, except I won't bring back the ,solarized-fg.... style named colors.

**Comment by bbatsov** [comment]
> That change was one of my first contributiions to any elisp package so I guess that the design would look different If i did it today even though it's still a quick but slightly dirty way to get it working.
> A macro that sets up colors is probably a more (e)lispy way of doing it so that the child theme isn't referring to variables let bound outside of it's context.

Such features are not common and I'd rather us not deal with them. As you're seeing right now - adding something unlikely to be used still adds some maintenance overhead. Overhead we can easily live without...

**Comment by thomasf** [comment]
If ever done, #18 also needs very similar changes due to required refactorings to keep things readable. In any case I rather see that the requirements of #18 would specify any kind of larger change like that.

**Comment by thomasf** [comment]
I reverted the change, child themes are back as they were before.
