### ISSUE TITLE
Why is the mode-line underlined?

### ISSUE THREAD

**Issue by rye** [bbatsov/solarized-emacs#187]
It really doesn't make any sense to me to have the mode-line be completely underlined. Just seems like clutter. Is there a reason why this is the case? Is this the case in the Vim package? If not, why here?

**Comment by thomasf** [comment]
Its because it separates the mode line and header lines a bit more.

**Comment by thomasf** [comment]
![screen shot 2015-05-16 at 18 11 52](https://cloud.githubusercontent.com/assets/330847/7666918/1f916664-fbf7-11e4-809d-9b9f31a7c959.png)

**Comment by thomasf** [comment]
If you also use header lines alot it helps even more

**Comment by rye** [comment]
This is how it looks for me:

![screenshot from 2015-05-16 11 55 10](https://cloud.githubusercontent.com/assets/1566689/7667103/7bab6556-fbc2-11e4-8a1e-e5735e9a059a.png)

You can see the small amount of space on the bottom.

This seems related to #113.

**Comment by thomasf** [comment]
this setting "fixes" that (even for non X environments) https://github.com/bbatsov/solarized-emacs#underline-position-setting-for-x

**Comment by rye** [comment]
I found that right as you sent it. Thanks!

**Comment by thomasf** [comment]
the only downside is that a strong underline obscures underscores since they are bottom aligned as well.  IMHO this setting is generally preferable for code editing than the normal look anyway

**Comment by andschwa** [comment]
Wow, `(setq x-underline-at-descent-line t)` is so much better. Thanks!
