### ISSUE TITLE
New magit faces

### ISSUE THREAD

**Issue by expez** [bbatsov/solarized-emacs#191]
Hey, I just installed the new magit.  Are the new faces final?

The screenshot below represents one of the most common situations (at least for me): I've done some changes and I'm now hanging out in the magit-status window to review them.  

![ss](http://i.imgur.com/vPyGkZw.png)

The problem I have with this view is that it looks incredibly busy.  I think this is largely caused by the brown background, which is used to highlight the active section.

Could we possibly tone down the background a little?  I'd actually prefer if it was in the same color as the standard background, just a different shade.

**Comment by thomasf** [comment]
I also have a somewhat harder time than before reading diffs from top to bottom quickly due to all the colors.. It's better for the bright version of the theme.

**Comment by thomasf** [comment]
this issue is related to #134

**Comment by thomasf** [comment]
also maybe related to https://github.com/magit/magit/issues/1972

**Comment by kylev** [comment]
Out of the box with prelude and solarized-dark, magit is still pretty tough to use. The contrast on the reversed text is unreadable.

![Screen Shot 2019-09-09 at 6 24 29 PM](https://user-images.githubusercontent.com/46888/64576821-1c1b8500-d32f-11e9-8568-d1f684ebf8c7.png)

**Comment by jimmywongroo** [comment]
@kylev I cannot reproduce what you are seeing. Magit's faces haven't been changed in 5 years and Solarized also don't touch these Magit faces. Can you reproduce this with emacs -Q and only solarized and magit installed?

**Comment by wyuenho** [comment]
@kylev I cannot reproduce what you are seeing. Magit's faces haven't been changed in 5 years and Solarized also don't touch these Magit faces. Can you reproduce this with emacs -Q and only solarized and magit installed?

**Comment by wyuenho** [comment]
@kylev can you also move your point to the locations in question and type M-x describe-face and tell me what you see?

**Comment by kylev** [comment]
In the process of investigating, I discovered my mistake.

Emacs [prelude](https://github.com/bbatsov/prelude) has [special rules for installing themes](https://prelude.emacsredux.com/en/latest/configuration/#color-themes) and they _must_ be followed. Using `load-theme` will cause problems; themes under prelude set `prelude-theme` and need to be in the `personal/preload` config directory.

Consider my complaint an errant report, and allow this comment to be a monument to my foolishness (and hopefully an aide to others). 😄 

Now:
![Screen Shot 2019-10-11 at 3 54 50 PM](https://user-images.githubusercontent.com/46888/66689509-166fd280-ec40-11e9-8b87-69d2446c2b3a.png)

**Comment by expez** [comment]
FWIW this doesn't invalidate the original report.  I'm not using prelude.

**Comment by wyuenho** [comment]
@expez but solarized has switched to use a more subtle blueish background like in @kylev's screenshot for years?

**Comment by expez** [comment]
Then I guess we're done here!  Thanks!
