### ISSUE TITLE
Various diff/merge modes are broken

### ISSUE THREAD

**Issue by thomasf** [bbatsov/solarized-emacs#194]
Something entirely new needs to be done for this to work.. 
This is a meta issue.

Related issues: 
- #192 
- #191 
- #134

**Comment by PythonNut** [comment]
I took at stab at #192, but I couldn't figure out what the canonical diff face colors are. I know the faces in `magit` look very nice, but it turns out they're defined in `magit`, not here, and the colors they use aren't in the Solarized pallet.

**Comment by thomasf** [comment]
No, we need a totally new strategy.. It's probably impossible to do it properly with the standard solarized palette without making it a screaming mess.  To the magit diff faces are also only balanced against the bright theme, the contrasts are totally off in the dark one. 

All of the various diff/merge modes needs to be solved with something that works for all scenarios.

**Comment by thomasf** [comment]
I found some interesting work here: https://imgur.com/r/vim/50jbw
Not directly applicable to this theme but the we probably need to define good looking bg colors outside of the normal solarized palette which works well for both bright and dark

 
![image](https://user-images.githubusercontent.com/330847/37596714-5c1792c6-2b7d-11e8-9b16-81df8e770ef7.png)
![image](https://user-images.githubusercontent.com/330847/37596719-61ef07a6-2b7d-11e8-8d97-1e20b3999a3b.png)
![image](https://user-images.githubusercontent.com/330847/37596729-6620a0aa-2b7d-11e8-9c7a-f5f7685a7e67.png)
![image](https://user-images.githubusercontent.com/330847/37596733-6998d13a-2b7d-11e8-84df-450eb4bb866b.png)
![image](https://user-images.githubusercontent.com/330847/37596739-6f73eaae-2b7d-11e8-9b9e-276ef11807d8.png)
![image](https://user-images.githubusercontent.com/330847/37596746-73f6b08e-2b7d-11e8-8c16-04c626ae4d68.png)

**Comment by thomasf** [comment]
other color ideas as well: https://github.com/fentie/netbeans-colors-solarized/issues/9

It's quite painful process to run the manual test cycle of opening up a lot of diff/merge modes in both dark/bright for every change.. the process should probably be documented inside a special repostitory which has braches with conflicts and both trivial and complicated commit diffs.

**Comment by wyuenho** [comment]
I'm not too fond of the palette above, they don't strike me as very diffy.

This is what I have for my solarized config for now. Basically I've just aliased all the diff faces to magit's. Magit's faces are very well done, and fits perfectly in this theme. I'd just port them directly into solarized if I had the time.

```emacs-lisp
(dolist (entry '((ediff-current-diff-C . ((((class color) (background light))
                                             (:background "#DDEEFF" :foreground "#005588"))
                                            (((class color) (background dark))
                                             (:background "#005588" :foreground "#DDEEFF"))))
                   (ediff-fine-diff-C . ((((class color) (background light))
                                          (:background "#EEFFFF" :foreground "#006699"))
                                         (((class color) (background dark))
                                          (:background "#006699" :foreground "#EEFFFF"))))))
    (let ((face (car entry))
          (spec (cdr entry)))
      (put face 'theme-face nil)
      (face-spec-set face spec)))

  (dolist (face-map '((diff-hl-insert              . magit-diff-added)
                      (diff-hl-change              . ediff-current-diff-C)
                      (diff-hl-delete              . magit-diff-removed)
                      (smerge-base                 . magit-diff-base)
                      (smerge-lower                . magit-diff-added)
                      (smerge-markers              . magit-diff-conflict-heading)
                      (smerge-refined-added        . magit-diff-added-highlight)
                      (smerge-refined-removed      . magit-diff-removed-highlight)
                      (smerge-upper                . magit-diff-removed)
                      (ediff-even-diff-A           . magit-diff-context-highlight)
                      (ediff-even-diff-Ancestor    . magit-diff-context)
                      (ediff-even-diff-B           . magit-diff-context-highlight)
                      (ediff-even-diff-C           . magit-diff-context-highlight)
                      (ediff-odd-diff-A            . magit-diff-context-highlight)
                      (ediff-odd-diff-Ancestor     . magit-diff-context)
                      (ediff-odd-diff-B            . magit-diff-context-highlight)
                      (ediff-odd-diff-C            . magit-diff-context-highlight)
                      (ediff-current-diff-A        . magit-diff-our)
                      (ediff-current-diff-Ancestor . magit-diff-base)
                      (ediff-current-diff-B        . magit-diff-their)
                      (ediff-fine-diff-A           . magit-diff-removed-highlight)
                      (ediff-fine-diff-Ancestor    . magit-diff-base-highlight)
                      (ediff-fine-diff-B           . magit-diff-added-highlight)
                      (diff-header                 . magit-diff-hunk-heading)
                      (diff-context                . magit-diff-context)
                      (diff-added                  . magit-diff-added)
                      (diff-removed                . magit-diff-removed)
                      (diff-changed                . smerge-refined-changed)
                      (diff-refine-added           . magit-diff-added-highlight)
                      (diff-refine-removed         . magit-diff-removed-highlight)
                      (diff-refine-changed         . ediff-fine-diff-C)
                      (diff-indicator-added        . magit-diffstat-added)
                      (diff-indicator-removed      . magit-diffstat-removed)))
    (let* ((face (car face-map))
           (alias (cdr face-map)))
      (put face 'theme-face nil)
      (put face 'face-alias alias)))
```

**Comment by wyuenho** [comment]
Preview with [fontify-face-mode](https://github.com/Fuco1/fontify-face):

<img width="708" alt="screen shot 2018-06-20 at 16 38 17" src="https://user-images.githubusercontent.com/160028/41668933-68f89dfe-74a8-11e8-9c83-ee1bf21c4392.png">

**Comment by alphapapa** [comment]
@wyuenho They don't look bad, but those aren't Solarized colors.

**Comment by wyuenho** [comment]
They don't have to be, and they can't. See https://github.com/bbatsov/solarized-emacs/pull/282#issuecomment-373768835

**Comment by alphapapa** [comment]
I don't understand your point. 

This is the Solarized theme. It doesn't make sense to use colors that are not at least derived from Solarized colors. If you want other colors, you should release a complementary package that changes faces on top of this package, or just customize it in your personal config.

**Comment by wyuenho** [comment]
The point is, it's futile to derive diff colors from the regular solarized palette. The requirements are:

1. One hue for each diff op -> ancester, added, removed and merged,
2. Two shades for each of 1) -> a foreground and a background, and foreground must be legible on background, i.e the lightness between fg and bg must be far apart.
3. A lighter variant of each of 2) for fine grained word diff.

That's 16 extra colors spread across 4 different hues. Now when you look at the standard palette in `solarized-with-color-variables`, there are 8 hues with just 2 shades each that are not particularly far apart. Deriving from them is certainly possible, but as soon as you get away from that palette, it's not really Solorized anymore is it? So what's the difference of using a different palette? Mind you the existing themed diff faces are already deriving from the standard palette, and they don't look very good or even legible.

**Comment by alphapapa** [comment]
> Deriving from them is certainly possible, but as soon as you get away from that palette, it's not really Solorized anymore is it? So what's the difference of using a different palette?

I don't understand your point.  No, it wouldn't be canonical Solarized, but darkening/lightening/saturating/desaturating canonical Solarized colors would look like a theme derived from Solarized.  You seem to be proposing using a completely different set of colors which bear no relation to Solarized.  That makes no sense in a Solarized theme.  If you prefer those colors, that's fine, but they belong in another package or your personal config.

**Comment by thomasf** [comment]
IMHO, It doesn't really matter what the colors are as long as they look to fit in somewhat..  One problem with trying to derive stuff closer from the default accent colors is that there is so little contrast space to work with that it usually just becomes very hard to see differences until you have modified the colors so much that they are quite far away from the original colors anyway.

**Comment by alphapapa** [comment]
@thomasf Maybe an option is needed to enable higher contrast diffs. That would preserve the "Solarizedness" of the theme while allowing more diff contrast for those who need it.
