### ISSUE TITLE
child theme use

### ISSUE THREAD

**Issue by blaenk** [bbatsov/solarized-emacs#196]
I was very excited when I saw that child themes were possible in this. The ability to reuse the solarized color variables and layer customizations on top of the theme is amazing, since you don't have to hack on and fork the theme itself.

I can't seem to get it to work though. I am able to `load-theme` it, but my customizations aren't showing up. I emit a `(message "test")` to make sure the theme function is being called, it is.

I have this in `init.el`:

``` elisp
(defun solarized-blaenk-theme ()
  "My solarized child theme."
  (message "written")
  (custom-theme-set-faces
   theme-name
   `(default ((,class (:foreground ,red :background ,base03))))
   `(rainbow-blocks-depth-1-face ((,class (:foreground ,red))))
   ))

(provide 'solarized-blaenk)
(load-theme 'solarized-blaenk-light t)
```

This is what I have in ~/.emacs.d/themes which is in my custom theme load path:

``` elisp
(require 'solarized)
(require 'solarized-blaenk)

;; This files needs to be places iside the custom-theme-load-path list
(deftheme solarized-blaenk-light "The light variant of the Solarized colour theme")
(create-solarized-theme 'light 'solarized-blaenk-light 'solarized-blaenk-theme)

(provide-theme 'solarized-blaenk-light)
```

I'm not sure if that's how you're supposed to split it up; I'm new to emacs.

As is, solarized light does load but the customizations aren't showing up. The interesting (?) thing is that if I go to the theme file which includes the `deftheme` call and I `M-x eval-buffer`, my customizations _do_ show up as I would expect (i.e. the default font face shows up red).

What am I doing wrong? I really really want to get this to work, it sounds like an awesome feature :)

**Comment by blaenk** [comment]
Perhaps `theme-name` in `solarized-blaenk-theme` should be `'solarized-blaenk-light`? I just copied what was in the child theme example. I changed it though and that had no effect.

**Comment by blaenk** [comment]
It works if I add this line after my `load-theme` line:

``` elisp
(create-solarized-theme 'light 'solarized-blaenk-light 'solarized-blaenk-theme)
```

Perhaps it's something to do with load order?

**Comment by blaenk** [comment]
After playing around with it I noticed that consecutive calls to `custom-theme-set-faces` don't take effect. I think that may be the root of the issue.

**Comment by blaenk** [comment]
Trying to figure things out in this [stackexchange thread](http://emacs.stackexchange.com/questions/14205/redefine-theme-spec).

**Comment by thomasf** [comment]
IIIRC faces won't be applied two times which means that faces not defined by solarized.el still works in the child theme.. I don't have time to look into it atm.

**Comment by jyp** [comment]
I've tried creating a child theme, and I have exactly the same issue as you have. You seem to have found a solution for yourself but I can't figure out how to use it. Could you update the example child themes, or somehow explain your workaround?

**Comment by blaenk** [comment]
Child themes don't work AFAIK. I contributed a macro that basically exposes the color variables for you to customize faces manually. You can see how I do it [here](https://github.com/blaenk/dots/blob/d928a76d802159960d8b2768c660919924e99e44/emacs/.emacs.d/init.el#L521-L629).

**Comment by thomasf** [comment]
this is probably fixed now
