### ISSUE TITLE
js3-mode support

### ISSUE THREAD

**Issue by manuel-uberti** [bbatsov/solarized-emacs#204]
Would it be possible to add support for [js3-mode](https://github.com/thomblake/js3-mode)?

**Comment by PythonNut** [comment]
@manuel-uberti would this be as simple as copying the definitions from `js2-mode`?

**Comment by manuel-uberti** [comment]
@PythonNut probably, yes.

**Comment by PythonNut** [comment]
That's what I suspected, since they use the same font locking as far as I know. 

In that case, a PR would be trivial. I'll give it a shot soon.

**Comment by manuel-uberti** [comment]
Anything here? Should I close this issue?
