### ISSUE TITLE
Melpa: Solarized-theme not found

### ISSUE THREAD

**Issue by JC0nde** [bbatsov/solarized-emacs#216]
Hi, 
thanks for your nice prelude config! :-)
I also wanted to try your solarized-theme but when downloading it from melpa gives me that message:<br>
**url-insert-file-contents: https://melpa.org/packages/solarized-theme-20151211.535.tar: Not found**

...just to tell you.
have a great day,
Jonathan

**Comment by thomasf** [comment]
That is an old version.. you need to refresh your package contents.... 

How did you install? `M-x list-packages` should refresh the lists for you.. If that is so you maybe you don't have melpa in your `package-archives` variable.

**Comment by thomasf** [comment]
At this moment the correct version is https://melpa.org/packages/solarized-theme-20160106.15.tar

**Comment by JC0nde** [comment]
Hi, thanks for the quick reply.
damn... i didn't know doing the `M-x package-install "package"` didn't install a fresh one :P
...and of course `M-x list-packages` solved the problem, thank you very much!

**Comment by hakunin** [comment]
Hey guys, emacs noob here. Just installed emacs, trying to install the theme, package-install shows  me this and there seems to be no `solarized-theme`.

Any ideas?
![screenshot 2017-07-16 19 33 38](https://user-images.githubusercontent.com/65846/28249824-af35296e-6a5d-11e7-908c-a05760d6f515.png)
