### ISSUE TITLE
`Undefined custom theme` error when choosing `solarized` in `load-theme`

### ISSUE THREAD

**Issue by srustamo** [bbatsov/solarized-emacs#218]
The other two themes - `solarized-light` and `solarized-dark` - show up in the `customize-theme` and `load-theme` and can be chosen and set. The third - `solarized` - theme is also on the list, but selecting it produces the `Undefined custom theme` error.

**Comment by marinintim** [comment]
Probably easier to fix README.

**Comment by gustavjf** [comment]
Is manual installation recommended for the time being?

**Comment by thomasf** [comment]
I don't have this problem.. 

What version of emacs are you using?

**Comment by thomasf** [comment]
For a short time yesterday there was a broken commit pushed to this repository but it was fixed quite fast and it was about 20 hours ago so it's unlikely that it ever reached melpa.

**Comment by gustavjf** [comment]
24.5.1

All right, likely that melpa hasn't sync'ed yet.

**Comment by gustavjf** [comment]
Tried deleting and installing from melpa again, same issue. Let me know if I can provide any more information.

**Comment by thomasf** [comment]
How do you initialize and load the theme?

An init.el with only these things works for me:

**sol-init.el**:
```el
   (package-initialize)
   (load-theme 'solarized-dark)
```

```sh
emacs -q -l sol-init.el
```

**Comment by thomasf** [comment]
oh,. I see the context now I missed it a bit.  the `solarized` one is not supposed to work as a theme

**Comment by gustavjf** [comment]
Got it, thanks!
