### ISSUE TITLE
Disable border of the modeline

### ISSUE THREAD

**Issue by zxcvbn97** [bbatsov/solarized-emacs#220]
Hi there,

Is there anyway to disable the border of the modeline with solarized dark theme. The border is the gray line under the smart modeline in the attached image. Thanks!
![image](https://cloud.githubusercontent.com/assets/9757976/12768763/a579cf7e-c9d7-11e5-84dc-66c2196537f5.png)

**Comment by thomasf** [comment]
Setting `solarized-high-contrast-mode-line` to `t` might do what you want.. 

The theme in the picture doesnt look like it's using the solarized palette though.

This is how smart mode line looks with this theme:

![image](https://cloud.githubusercontent.com/assets/330847/13534409/3d79d448-e235-11e5-80ba-e1e7b0f986db.png)

**Comment by divansantana** [comment]
@thomasf that does indeed work around the border issue. However I'm using solarized-dark so would like the dark modeline however without the border - is that possible?

A similar issue is reported https://github.com/TheBB/spaceline/issues/59 but the suggested workaround there doesn't work.

**Comment by wyuenho** [comment]
Due to #223, is there any movement for this ticket?

Using the config recommended by [moody](https://github.com/tarsius/moody) at the bottom of the README, my mode line now looks like this:

<img width="706" alt="screen shot 2018-06-20 at 16 16 48" src="https://user-images.githubusercontent.com/160028/41667636-5cfdcdc4-74a5-11e8-86c8-91ebb5f1378e.png">

I really think ^ should be the default.

**Comment by purcell** [comment]
FWIW, this find border line below the mode-line appears to be the result of `window-divider-mode`, added in Emacs 25.1. In my own themes I'm explicitly setting custom variables to control that mode, so you might like to do that in this theme too. (I found this via [this stackoverflow answer](https://emacs.stackexchange.com/questions/29873/whats-this-line-between-the-modeline-and-the-echo-area).)

**Comment by minad** [comment]
Setting `:underline nil` fixes this. I am using something like the following to make adjustments to enabled themes.

~~~ elisp
;; apply some adjustments after theme switching
(advice-add #'enable-theme :after
            (lambda (&rest _)
              (set-face-attribute 'mode-line nil :height 0.8 :underline nil)
              (set-face-attribute 'mode-line-inactive nil :inherit 'mode-line :height 1.0 :underline nil)))
~~~
