### ISSUE TITLE
Wrong # of arguments

### ISSUE THREAD

**Issue by ilintault** [bbatsov/solarized-emacs#222]
*ERROR*: Wrong number of arguments: #[(name description color-definitions) "\303\304E\305\306\30D                         16:46
F\310\30DDF\207" [name description color-definitions progn deftheme apply (quote custom-theme-set-faces) quote provide-theme] 6], 2

when trying to load the theme

OS X 
GNU Emacs 24.5.1

**Comment by thomasf** [comment]
cannot repdocude
