### ISSUE TITLE
add missing avy faces

### ISSUE THREAD

**Issue by wbolster** [bbatsov/solarized-emacs#224]
Currently the theme defines only a subset of the faces used by `avy`, causing the screen to be come unreadable in various cases (when `avy-background t` for example). Please add these so that it becomes usable both in light and  dark modes:

```diff
modified   Emacs/elpa/solarized-theme-20160311.1447/solarized.el
@@ -525,7 +525,9 @@ customize the resulting theme."
 ;;;;; avy-mode
      `(avy-lead-face ((,class (:inherit isearch))))
      `(avy-lead-face-0 ((,class (:inherit isearch :background ,violet))))
+     `(avy-lead-face-1 ((,class (:inherit isearch :background ,orange))))
      `(avy-lead-face-2 ((,class (:inherit isearch :background ,cyan))))
+     `(avy-background-face ((,class (:inherit font-lock-comment-face))))
 ;;;;; bm
      `(bm-face ((,class (:overline ,base0))))
      `(bm-fringe-face ((,class (:overline ,base0))))
```

Note that the `avy-background-face` is not used in a default `avy` configuration. It is intended to "dim" everything except the jump characters, and using the same face as code comments does wonders.

**Comment by wbolster** [comment]
Obligatory screenshots (with `avy-background t`):

![image](https://cloud.githubusercontent.com/assets/748944/13982685/b86b0072-f0eb-11e5-9e47-be9a1f22af5f.png)

![image](https://cloud.githubusercontent.com/assets/748944/13982696/c2e8cae8-f0eb-11e5-878a-0a6fd86a5996.png)

**Comment by wbolster** [comment]
is there anything i can do to move this issue forward?

**Comment by bbatsov** [comment]
Convert it to a PR. :-)
