### ISSUE TITLE
Powerline on Solarized light

### ISSUE THREAD

**Issue by manuel-uberti** [bbatsov/solarized-emacs#229]
On a frame split in two, the inactive powerline looks kind of messy:

![2016-05-03-202535_1920x1080_scrot](https://cloud.githubusercontent.com/assets/8199224/14993870/32315b62-116d-11e6-9077-6d4184d17ecf.png)

I'm referring to the bit between the modes and the lines and columns numbers. Is this the expected behaviour?

**Comment by thomasf** [comment]
it's not intended, it looks messy.

**Comment by manuel-uberti** [comment]
any progress on this? :)

**Comment by manuel-uberti** [comment]
Could be related to this: https://github.com/milkypostman/powerline/issues/120

Looks like there is no solution, should I close this issue?

**Comment by manuel-uberti** [comment]
Probably this could be the right fix: https://github.com/milkypostman/powerline/pull/134

Waiting for it to be merged. I'll report back.

**Comment by manuel-uberti** [comment]
That fix doesn't work. There seems to be no interest in this, I'll close it. Feel free to re-open if it gets addressed by a fix.
