### ISSUE TITLE
highlight-parentheses support

### ISSUE THREAD

**Issue by wbolster** [bbatsov/solarized-emacs#241]
what would make sense for highlighted parentheses colouring? it looks like this in the theme:

```
+;;;;; highlight-parentheses  (TODO)
+     `(hl-paren-colors '(,orange ,violet ,cyan ,green))
```

...but i'm not happy about how it looks. note that the defaults are even uglier. :)

**Comment by thomasf** [comment]
It's very hard to do that properly.. Does the the same color sequence as rainbow-delimiters use work better?

**Comment by wbolster** [comment]
yeah i guess that sequence is better. the colors are a bit "in your face" anyway, which is the whole point of `highlight-parentheses` anyway, so i guess it's ok. it's only local context anyway, so a bit of a disco lights show is not necessarily bad.

**Comment by wbolster** [comment]
thanks @LeandroCardoso !
