### ISSUE TITLE
Generating htmlize css

### ISSUE THREAD

**Issue by done-with-fish** [bbatsov/solarized-emacs#247]
Issuing `M-x org-html-htmlize-generate-css` yields the error 

`face-attribute: Invalid face: nxml-char-ref-number`

I'm not sure how to fix this.

**Comment by thomasf** [comment]
hmm,. I see that the kite faces are inheriting from `nxml-char-ref-number` which actually is defined in nxml-mode...

Can you maybe try search and replacing all instances of `nxml-char-ref-number` with `font-lock-constant-face` in your solarized.el and tell me if that resolves the problem for you?

**Comment by done-with-fish** [comment]
After making the replacements I'm now met with `Invalid face: font-lock-string`.

**Comment by thomasf** [comment]
I did a few modifications of invalid face definitions which looked like potential trouble makers, it's worth mentioning that `org-html-htmlize-generate-css` works for me regardless of these changes so I can't reproduce.

**Comment by done-with-fish** [comment]
After updating I'm now getting `Invalid face: change-log-file`.

**Comment by done-with-fish** [comment]
As a side note, maybe someone could post the css file generated with this command here?

**Comment by thomasf** [comment]
It seems like many of the kite faces references other faces which are wrong or not loaded.. `change-log-file` is actually in vc's `add-log` package but you probably haven't loaded that one.. If you just keep replacing the names with `default` until you don't see any errors anymore and then tell me which they were afterwards I can probably fix the situation. 

Maybe you have an old `htmlize` package or something?

**Comment by done-with-fish** [comment]
I updated `htmlize` today with no new results.

After changing names with `default` I eventually got to `Invalid face: font-lock-pseudo-keyword-face`, which I can't find!

**Comment by thomasf** [comment]
Your whole problem is coming from faces which cannot be found, you probably have some package installed which inherits from `font-lock-pseudo-keyword-face` which isn't available.  I guess you could search for that string within your emacs.d directory, it's probably there somewhere.

**Comment by thomasf** [comment]
it would be great if you could tell me which the ones in `solarized.el` were so that I can remove those, it's no point referencing faces which doesn't exist

**Comment by done-with-fish** [comment]
I changed each of the following to `default`:

- ecb-history-bucket-node-face
- ecb-history-general-face
- ecb-default-general-face
- ecb-analyse-general-face
- ecb-default-general-face
- ecb-methods-general-face
- ecb-default-general-face
- css-property
- css-proprietary-property
- css-selector
- change-log-file

Grepping my `~/.emacs.d/` directory for `font-lock-pseudo-keyword-face` yields zero results.
