### ISSUE TITLE
Underline in mode-line of light theme

### ISSUE THREAD

**Issue by gujiaxi** [bbatsov/solarized-emacs#248]
I know this underline in lighter version of solarized is for distinguishing mode-line and minibuffer but I prefer to have a custom variable to show or hide it. Moreover, such a variable can make both light and dark version consistent.

`(setq x-underline-at-descent-line t)` is actually not a good idea as it takes side effects globally instead of only within solarized-theme.

**Comment by thomasf** [comment]
I guess the effects of `x-underline-at-descent-line` might differ a tiny bit depending on the font but other than the fact that is `_` is a bit harder to see I actually think that it makes the text display better overall..

IIRC, setting `solarized-high-contrast-mode-line` to `nil` disables the underline as a separator thing.
