### ISSUE TITLE
Error installing/compiling the package

### ISSUE THREAD

**Issue by RafalLukawiecki** [bbatsov/solarized-emacs#257]
My apologies if this is my error, but I just cannot find any references to it elsewhere. When I try to package-install your theme, I get these 4 compilation errors, each "Symbol’s value as variable is void: read:errno=54". Any suggestions would be appreciated, thank you.

<img width="1016" alt="screen shot 2017-03-11 at 20 41 15" src="https://cloud.githubusercontent.com/assets/22912705/23826753/3d2ec2ba-069b-11e7-8a05-b72de75b52e9.png">

This is on GNU Emacs 25.1.1 on macOS.

**Comment by thomasf** [comment]
Seels like there might have been an package installation problem or something similar.. try to delete the installed pakcage, refresh the package list and reinstall...

**Comment by RafalLukawiecki** [comment]
Thank you, @thomasf. I had to delete the emacs.d/elpa directory and I have reset my emacs.d, and I am pleased to say that the theme has now compiled, and it works in the GUI. Unfortunately, colous are wrong in the iTerm2... I am subscribing to https://github.com/bbatsov/solarized-emacs/issues/18...
