### ISSUE TITLE
Markdown: no font / colour difference between title hierarchies: # = ## = ###

### ISSUE THREAD

**Issue by dennismayr** [bbatsov/solarized-emacs#273]
Hi,
Emacs newcomer here.

I just tested `solarized-theme`, and it's easy on the eyes; however, I just found that in Markdown mode, there's no font size / colour difference between title hierarchies: #, ##, ###. This makes some documents a bit harder to read.

Example:
![captura de pantalla de 2017-10-13 20-00-55](https://user-images.githubusercontent.com/30353238/31569540-ea920ace-b051-11e7-84ef-1303b8ba45b0.png)

Reference: spacemacs-theme:
![captura de pantalla de 2017-10-13 20-01-14](https://user-images.githubusercontent.com/30353238/31569550-fb478cd6-b051-11e7-9a9d-9087558d66ad.png)

How can this be modified?

**Comment by dennismayr** [comment]
*bump*

**Comment by dcherian** [comment]
Move your cursor over the heading; `M-x describe-face`; that will tell you which face to modify.

Then for example, you could do something like this
```
(set-face-attribute 'org-target nil
		      :foreground "#586e75"
		      :background nil)
```

**Comment by dennismayr** [comment]
Thanks for the tip! I'll look into this over the weekend.

**Comment by thomasf** [comment]
I think that we used to have that but some times it can be very annoying.. This is true for both rst-mode and markdown-mode IIRC:

these are valid header formats:
![image](https://user-images.githubusercontent.com/330847/40716770-5d324474-640a-11e8-83fb-73abdc2098be.png)

Still valid formatting but the `===` doesnt align correctly to the header text size anymore:

**Comment by thomasf** [comment]
There used to be multiple colors for heading level as well but it was removed because in a lot of document it just becomes a color soup instgead of making it easier to read.

**Comment by dennismayr** [comment]
Still, even if there's no colour difference, different font size/weight/style improves readability without turning the document into a color soup.
