### ISSUE TITLE
Checking to see if this is a problem on my end

### ISSUE THREAD

**Issue by Wagk** [bbatsov/solarized-emacs#278]
Hello, I'm experiencing an issue where the theme would have a background of a different color while using putty, and would like to check if other people here have experienced the same issue prior

The left of the image is GUI, and the right, a putty terminal

![image](https://i.imgur.com/7fO71H4.jpg)

**Comment by articuluxe** [comment]
for what it’s worth I see this not only in putty but also in terminals on Linux and MacOS. Themes with dark backgrounds, like solarized, often show as blue. I’ve always assumed it was a limitation of using 256 colors.

**Comment by thomasf** [comment]
Yeah, this theme doesnt really work well in terminals due to several reasons.. It's possible to get it to work better than that with some work but it's not great.. There are other open issues and an pull request already regarding this so closing.
