### ISSUE TITLE
Problem with Company

### ISSUE THREAD

**Issue by NightMachinary** [bbatsov/solarized-emacs#287]
As you can see:
![image](https://user-images.githubusercontent.com/36224762/37247960-13f9a064-24da-11e8-97ff-d00bb3ff8884.png)

**Comment by anarcat** [comment]
it's not obvious to me what the problem is from the screenshot, could you describe it with words?

**Comment by NightMachinary** [comment]
@anarcat The color of the highlighted line is the same as that of the popup.

**Comment by thomasf** [comment]
I just pushed new company facedefs..

**Comment by thomasf** [comment]
https://github.com/bbatsov/solarized-emacs/pull/296#issuecomment-392860885 for reference
