### ISSUE TITLE
Org-mode source blocks foreground colour wrong (26.1)

### ISSUE THREAD

**Issue by hkmix** [bbatsov/solarized-emacs#297]
Just updated to 26.1 on macOS and Linux, and looks like source blocks are using the comment colour as the default foreground colour:

![emacs-org-fg](https://user-images.githubusercontent.com/8205094/40694404-65993d0a-638a-11e8-81eb-591c04ff653c.png)

whereas it should be like this (after `C-c '`):

![emacs-org-correct](https://user-images.githubusercontent.com/8205094/40694664-9566c4d4-638b-11e8-8166-94be7f4c3365.png)

MWE:

```org
#+BEGIN_SRC emacs-lisp
  (print "hello world")
#+END_SRC
```

Does it have anything to do with the new `org-src-block-faces` alist? Not a super-experienced Emacs user so let me know if something is not clear.

EDIT:

This happens with all languages, not just elisp.

**Comment by hkmix** [comment]
Good call, it works on my end with the following:

```diff
1680c1680
<      `(org-block ((,class (:foreground ,base01))))
---
>      `(org-block ((,class (:foreground ,base0))))
```

Out of curiosity, why was `org-block` changed to use `base01`? The documentation for it suggests it shouldn't have been set to this:

```
org-block is also a face.

Face: org-block (sample) (customize this face)

Documentation:
Face text in #+begin ... #+end blocks.
For source-blocks ‘org-src-block-faces’ takes precedence.
See also ‘org-fontify-quote-and-verse-blocks’.
```

**Comment by thomasf** [comment]
it did not take precedence earlier..

**Comment by hkmix** [comment]
Oops, sorry, I just realized I phrased my question poorly. What I meant to ask was "What is the goal of setting the foreground of `org-block` to use the comment foreground?" Is it so that code that does not use a recognized Org type is set to the comment colour?

**Comment by thomasf** [comment]
![image](https://user-images.githubusercontent.com/330847/40763184-353bc298-64a4-11e8-8b4c-6ed777af2fc8.png)

**Comment by hkmix** [comment]
Thanks for the fix!
