### ISSUE TITLE
Wrong colors?

### ISSUE THREAD

**Issue by martinweiss** [bbatsov/solarized-emacs#317]
I am using terminal Emacs 25.1.1 on a Raspberry Pi Zero W running Raspbian Stretch. When I set the theme so solarized-dark, I get a blue screen.

Here's a screenshot: 
![screenshot](https://i.imgur.com/ferA16E.png)

Could anyone please help me figure out what's wrong?

**Comment by thomasf** [comment]
duplicate of #18
