### ISSUE TITLE
GUI vs iTerm2 magit colors in dark theme

### ISSUE THREAD

**Issue by srustamo** [bbatsov/solarized-emacs#319]
I can't figure out why, with the same config files used, the colors in 24bit terminal and GUI differ in dark mode. Any ideas? 

GUI screenshot

<img width="878" alt="screenshot 2018-12-12 14 47 24" src="https://user-images.githubusercontent.com/749813/49861853-a7a6ca80-fe1e-11e8-95d7-3dbce97265c8.png">

iTerm2 24bit sceenshot

![screenshot 2018-12-12 14 47 33](https://user-images.githubusercontent.com/749813/49861896-c1481200-fe1e-11e8-896a-836e7be842db.png)

**Comment by conao3** [comment]
The two environments do not have the same color expressiveness. That you have already written.
If there are colors that are difficult to see depending on the number of colors, you can suggest them by PR or issue for the face.

**Comment by thomasf** [comment]
I can confirm that the current master version works with alacritty with a 24bit terminfo

**Comment by thomasf** [comment]
the result above might be cause TERM isn't correctly configured or the terminfo is specified wrong.
