### ISSUE TITLE
Screenshots missing

### ISSUE THREAD

**Issue by indrajithi** [bbatsov/solarized-emacs#329]
It would be helpful if we can add some screenshots of the theme.

**Comment by manuel-uberti** [comment]
There some screenshots here: https://emacsthemes.com/themes/solarized-themes.html

@bbatsov  Probably a link to them in the README should be enough. :)

**Comment by bbatsov** [comment]
That's true, although I guess we can add something to the repo as well.

**Comment by thomasf** [comment]
I guess there is a lot less activity here than it used to be but I have not wanted to have screenshots because of the burden of updating them when facedefs changes and the possibility of not remembering to update them
