### ISSUE TITLE
Reversed foreground/background for face attributes

### ISSUE THREAD

**Issue by cassebas** [bbatsov/solarized-emacs#334]
Hi,
I just discovered that when I use this package (which I like very much:), strange thing happens for this piece of code:
```
(defun my-whitespace-settings (frame whitespace-color)
  (set-face-attribute 'whitespace-tab frame
                      :foreground "Black"
                      :background "Green"))
```
I get a trailing tab with a black background and green foreground (so the foreground and background are reversed). This doesn't happen when I don't `(load-theme solarized-dark t))`

Could this be a bug of solarized-emacs?
Thnx!

**Comment by mallt** [comment]
The swapping of colors is caused by the [`inverse-video` attribute of the `whitespace-tab` face](https://github.com/bbatsov/solarized-emacs/blob/master/solarized.el#L2261). You can disable this by setting the `inverse-video` attribute to nil:
``` elisp
(set-face-attribute 'whitespace-tab nil
                    :foreground "black"
                    :background "green"
                    :inverse-video nil)
```
