### ISSUE TITLE
solarized-with-color-variables is broken

### ISSUE THREAD

**Issue by blaenk** [bbatsov/solarized-emacs#366]
I contributed this macro way back. From what I gather there are some major changes/refactorings going on, but just in case it was a mistake, `solarized-with-color-variables` appears to be broken.

Its intention is to evaluate the macro's body within a `let` environment with the color variables bound, to allow the colors to be used for anything (such as `setq`'s or whatever), but this is no longer possible. ~~The docstring still references a `BODY` parameter but it no longer exists in its function definition. Now this macro seems to effect theme changes through `custom-theme-set-faces`.~~

I think the general idea of being able to access the colors without side-effects has proven to be very useful, whether it be by this macro or some other way.

**Comment by conao3** [comment]
Please show me *broken* example. Then I can investigate it.

**Comment by conao3** [comment]
I understand. Use *child-theme* feature instead. Please see https://github.com/bbatsov/solarized-emacs/blob/master/UPGRADE-GUIDE.md

**Comment by blaenk** [comment]
Thanks @conao3
