### ISSUE TITLE
packaging: Split (m)ELPA package into multiple packages

### ISSUE THREAD

**Issue by thomasf** [bbatsov/solarized-emacs#369]
**draft**

## Splitting off extra themes

These themes will be included in main package

- solarized-dark-theme.el
- solarized-light-theme.el
- solarized-dark-high-contrast-theme.el
- solarized-light-high-contrast-theme.el

These will be in a seprate package (maybe solarized-extra-themes or something similar)
- solarized-gruvbox-dark-theme.el
- solarized-gruvbox-light-theme.el
- solarized-zenburn-theme.el
- solarized-wombat-dark-theme.el

**Comment by conao3** [comment]
And each color theme has its own palette in its own file.
That way we can remove `eval-when-compile` and get a better view.

**Comment by thomasf** [comment]
> And each color theme has its own palette in its own file.
> That way we can remove `eval-when-compile` and get a better view.

Child themes has to be able to require those palettes without casing themes to be defined though. Each palette could maybe have it's own file, idk. Will have to think about that.

**Comment by thomasf** [comment]
This is just work that I am not prepared to do because of the low returns so unless someone else does all of it, multiple elpa packages and all this will not be in v2.0.

 Looking towards a release v2.0 soonish so going through any breaking stuff like removing themes.

Removing the wombat theme though since it really is using the user defined theme code.

**Comment by thomasf** [comment]
not removing the wombat theme after all, i misremembered how it was implemented. It's better to not break things
