### ISSUE TITLE
Incorrect color 

### ISSUE THREAD

**Issue by vuquangtam** [bbatsov/solarized-emacs#375]
Recently i update newest version, solarized dark color pallete isn't the same previous version as well as vim's version.
In newest package:
![emacs](https://user-images.githubusercontent.com/6467819/69928685-031a0e80-14ef-11ea-907c-996965c39b5b.png)
In vim (as well as older package)
![vim](https://user-images.githubusercontent.com/6467819/69928686-031a0e80-14ef-11ea-8c9f-9e2db6531db8.png)

**Comment by thomasf** [comment]
yeah, this theme does not adhere to any upstream theming choices. We have not changed basic colors recently though so you probably arent using the same solarized theme.
