### ISSUE TITLE
Error changing theme

### ISSUE THREAD

**Issue by pbgc** [bbatsov/solarized-emacs#386]
Example:

Running Emacs with 

`(load-theme 'solarized-wombat-dark t)`

on init.el and then changing to any other solarized theme (by running code or by selecting on the *Custom Themes* buffer) gives (this error is for solarized-dark-contrast choosed):

```
Debugger entered--Lisp error: (invalid-function "#3c6e408d329c")
  ("#3c6e408d329c" "#0c4a45f54ce3" "#486d33913531" "#1fab3bea568c" "#2ec943ac3324" "#449935a6314d" "#0b03411b5985")
  eval(("#3c6e408d329c" "#0c4a45f54ce3" "#486d33913531" "#1fab3bea568c" "#2ec943ac3324" "#449935a6314d" "#0b03411b5985"))
  custom-theme-recalc-variable(highlight-symbol-colors)
  enable-theme(solarized-dark-high-contrast)
  load-theme(solarized-dark-high-contrast t)
  eval((load-theme (quote solarized-dark-high-contrast) t) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)



```

**Comment by conao3** [comment]
What solarized-theme version?
Please re-install package(remove `solarized-theme` from `elpa` folder and install it) and retry.

**Comment by pbgc** [comment]
> What solarized-theme version?
![Captura de ecrã 2019-12-10, às 13 13 58](https://user-images.githubusercontent.com/180825/70532471-06487680-1b4f-11ea-948c-41ef0991422d.png)

> Please re-install package(remove solarized-theme from elpa folder and install it) and retry.
Done that several times before submitting the issue. Done it one more time. Same error.
The theme works great when emacs is launched. The error only occurs when trying to change to another solarized theme with a previous already selected.

**Comment by conao3** [comment]
Thanks, I try to regenerate your issue.

**Comment by pbgc** [comment]
I just discovered that the problem is cause by the highlight-symbol package.
On the error on the original issue you can read the line: custom-theme-recalc-variable(highlight-symbol-colors)

Now I'm having this error when lauching Emacs with one of the Solarized Themes defined:

`Debugger entered--Lisp error: (invalid-function "#551b4b293a05")
  ("#551b4b293a05" "#3f214d7540e0" "#5a1a48ea46fe" "#3fbe327642ee" "#42724c8355d4" "#536946893a1a" "#46c448dd5357")
  eval(("#551b4b293a05" "#3f214d7540e0" "#5a1a48ea46fe" "#3fbe327642ee" "#42724c8355d4" "#536946893a1a" "#46c448dd5357"))
  custom-initialize-reset(highlight-symbol-colors (quote ("yellow" "DeepPink" "cyan" "MediumPurple1" "SpringGreen1" "DarkOrange" "HotPink1" "RoyalBlue1" "OliveDrab")))
  custom-declare-variable(highlight-symbol-colors (quote ("yellow" "DeepPink" "cyan" "MediumPurple1" "SpringGreen1" "DarkOrange" "HotPink1" "RoyalBlue1" "OliveDrab")) "Colors and/or faces used by `highlight-symbol'.\nhighlighting the symbols will use these colors/faces in order." :type (repeat (choice color face)) :group highlight-symbol)
  byte-code("\300\301\302\303\304\305\306\307\310\311&\011\210\300\312\313\314\304\315\310\311&\007\210\300\316\317\320\304\321\310\311&\007\210\300\322\323\324\304\315\310\311&\007\210\300\325\326\327\304\330\310\311&\007\207" [custom-declare-variable highlight-symbol-idle-delay 1.5 "Number of seconds of idle time before highlighting the current symbol.\nIf this variable is set to 0, no idle time is required.\nChanging this does not take effect until `highlight-symbol-mode' has been\ndisabled for all buffers." :type number :set highlight-symbol-set :group highlight-symbol highlight-symbol-highlight-single-occurrence t "Determines if `highlight-symbol-mode' highlights single occurrences.\nIf nil, `highlight-symbol-mode' will only highlight a symbol if there are\nmore occurrences in this buffer." boolean highlight-symbol-colors (quote ("yellow" "DeepPink" "cyan" "MediumPurple1" "SpringGreen1" "DarkOrange" "HotPink1" "RoyalBlue1" "OliveDrab")) "Colors and/or faces used by `highlight-symbol'.\nhighlighting the symbols will use these colors/faces in order." (repeat (choice color face)) highlight-symbol-on-navigation-p nil "Whether or not to temporarily highlight the symbol when using\n`highlight-symbol-jump' family of functions." highlight-symbol-ignore-list (quote nil) "List of regexp rules that specifies what symbols should not be highlighted." (repeat string)] 10)
  require(highlight-symbol)
  eval-buffer(#<buffer  *load*> nil "/Users/pbeck/.emacs" nil t)  ; Reading at buffer position 37286
  load-with-code-conversion("/Users/pbeck/.emacs" "/Users/pbeck/.emacs" t t)
  load("~/.emacs" t t)
  #f(compiled-function () #<bytecode 0x400d1a6d>)()
  command-line()
  normal-top-level()`

if I remove the line:

`(require 'highlight-symbol)`

all the errors go away .... BUT this is only happening with Solarized Theme. I tried with several others and have no problem ... and highlight-symbol is really a useful and used package

**Comment by pbgc** [comment]
@conao3 

the error also occurs without the highlight-symbol package ... if you try to run emacs  command: highlight-symbol-at-point (https://www.gnu.org/software/emacs/manual/html_node/emacs/Highlight-Interactively.html) the exact same error occurs! 

So it's not a problem with the hightlight-symbol package ... but from Solarized Theme

**Comment by pbgc** [comment]
@conao3 just installed and indeed is solved. Thanks!!!
I will close the issue.
