### ISSUE TITLE
Underspecification of magit-branch-local

### ISSUE THREAD

**Issue by DamienCassou** [bbatsov/solarized-emacs#390]
If I load them [zerodark](https://melpa.org/#/zerodark-theme) first and then solarized-light-hight-contrast, I get:

![2020-01-21-112844](https://user-images.githubusercontent.com/217543/72797654-cdb5b580-3c41-11ea-8fca-07964c0650fa.png)

This is hard to read for me.

**Comment by thomasf** [comment]
it probably works if you unload the zero dark theme first.  IIRC the emacs theme system is a bit weird and just keep loading themes on top of each other instead of unloading them by default when load-theme is called interactively.

**Comment by thomasf** [comment]
IIRC you can look ay the value of  `custom-enabled-themes` variable if you have multiple themes enabled at once.

**Comment by thomasf** [comment]
For purposes of theme development I use this function to ensure that I always unload all themes when loading a new one.  I don't know if there is an easily accessible build in way to do this without an extra function.

```el
(defun dev-disable-all-themes()
  (interactive)
  (dolist (v custom-enabled-themes)
    (disable-theme v)))
```

**Comment by DamienCassou** [comment]
It works, thank you! You may close the issue.
