### ISSUE TITLE
Add screenshot to README

### ISSUE THREAD

**Issue by skangas** [bbatsov/solarized-emacs#391]
It would be nice if you could add a screenshot to the README, since that is the most important information when looking for a theme. Two times have I been here, and both times have I scrolled up and down, concluded there was no screenshot, and almost had to go search the web when I noticed the text you have: click here for screenshots.

I suggest you link the Emacs themes page below the actual screenshot.

Thanks.

**Comment by thomasf** [comment]
I don't have time to maintain it. It would require a whole set of screenshots to even begin to scratch the surface of what the theme does so it would have to be automated and I don't have time to keep anything like that spinning.
