### ISSUE TITLE
How to turn on hight light for company

### ISSUE THREAD

**Issue by MorosithIi** [bbatsov/solarized-emacs#393]
Hello there, I'm using solarized with company-mode in aquamacs. But it doesn't hight light when show up completions. How should I fix it? Please help.
![image](https://user-images.githubusercontent.com/23580174/76156095-3c869980-6130-11ea-9f49-9cdf651898ac.png)

**Comment by mallt** [comment]
You can change the highlighting with the `company-tooltip-common` face, f.ex.:
````elisp
(set-face-attribute 'company-tooltip-common nil :foreground "#b58900")
````

**Comment by thomasf** [comment]
hmm, I have probably only used company with lsp-mode and it doesn't look like that there.. How it is configured when it looks like that?

For refenrence this is how company-lsp looks 

![image](https://user-images.githubusercontent.com/330847/76161188-2af1c180-6131-11ea-9966-60bf9adb45b4.png)

**Comment by thomasf** [comment]
These two are different and from what I understand that *should* be enough

```el
     `(company-tooltip-common ((,class (:foreground ,base0))))
     `(company-tooltip-common-selection ((,class (:weight bold))))
```

**Comment by thomasf** [comment]
Does your emacs properly draw bold fonts in general?

**Comment by MorosithIi** [comment]
> Does your emacs properly draw bold fonts in general?

Maybe that is the reason. Thanks for your reply.

**Comment by MorosithIi** [comment]
> You can change the highlighting with the `company-tooltip-common` face, f.ex.:
> 
> ```emacs-lisp
> (set-face-attribute 'company-tooltip-common nil :foreground "#b58900")
> ```

That works, Thanks.
