### ISSUE TITLE
Next release / addition to NonGNU ELPA

### ISSUE THREAD

**Issue by bbatsov** [bbatsov/solarized-emacs#426]
I've started submitting my packages to the new NonGNU ELPA repo and it'd be good to cut a new release of Solarized before doing this. I know that @thomasf had some plans for things that needed to be done for a 2.0 release, but given there was not much new development recently, I guess we can just label whatever we currently have as 2.0 and be done with it.

**Comment by thomasf** [comment]
Maybe.. I have narrowed the 2.0 list down quite a bit recently.

https://github.com/bbatsov/solarized-emacs/milestone/1

I would like to solve these things that might require breaking changes first but I never seem to have time to get to it so I don't know. Maybe it's a 3.0 thing.

It's a pretty short list right now but one of the item is both breaking `load-theme` and not properly overriding styles with child themes.

**Comment by thomasf** [comment]
So sure. Lets do a 2.0 and open a 3.0 milestone instead.

**Comment by thomasf** [comment]
I did release tag for v2.0.0 today from lastest master
