### ISSUE TITLE
Color not shown correctly on ssh

### ISSUE THREAD

**Issue by hengyuan-hu** [bbatsov/solarized-emacs#436]
I installed this theme on my Ubuntu machine and it works perfectly in both terminal and GUI mode. However, the color seems messed up when I ssh into the Ubuntu machine from a Mac.
<img width="827" alt="Screen Shot 2022-10-29 at 12 05 35 AM" src="https://user-images.githubusercontent.com/4728165/198818751-1f7b3475-2d87-4e0d-ba78-0c3202182504.png">

I also tried to install this theme locally on my Mac, it also works perfectly. `echo $TERM` returns `xterm-256color` on both machines. Any idea why it does not work properly on ssh? Is that due to the color represented differently on Mac vs Linux?

Thanks a lot!

**Comment by cosmin** [comment]
I have the same problem when using `emacsclient -t` locally, the theme works when running `emacs` directly, but when trying to connect via emacclient it looks blue like this. I had to stop using it as a result.

**Comment by thomasf** [comment]
This theme requires a 24bit terminal, I am not sure why xterm-256color supports 24bit, generally it should be xterm-24bit but in the end it is up to the local  terminal capabilites files to define what the TERM strings represents.

Look at an article like https://pisquare.osisoft.com/s/Blog-Detail/a8r1I000000GvXBQA0/console-things-getting-24bit-color-working-in-terminals

Copy/paste the text below to test actual 24bit support:

```sh
awk 'BEGIN{

s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;

for (colnum = 0; colnum<77; colnum++) {

r = 255-(colnum*255/76);

g = (colnum*510/76);

b = (colnum*255/76);

if (g>255) g = 510-g;

printf "\033[48;2;%d;%d;%dm", r,g,b;

printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;

printf "%s\033[0m", substr(s,colnum+1,1);

}

printf "\n";

}'
```

Generally I would expect something like `TERM=xterm-24bit` for a 24bit compatible terminal.

**Comment by hengyuan-hu** [comment]
Thank you for pointing out the 24bit terminal issue. 

After some search online. I found the simplest solution is to run `COLORTERM=truecolor emacs -nw` when using ssh if the emacs version is >=28. 

For order versions, the xterm-24bit can be added this way https://github.com/syl20bnr/spacemacs/wiki/Terminal.
