### ISSUE TITLE
Org mode title faces

### ISSUE THREAD

**Issue by swsnr** [bbatsov/solarized-emacs#82]
In 517fd96299fffc8ea67330280b76e9f66abb0c86, Org title faces were changed to use scaled variable pitch faces.

While we can argue about variable pitch, the scaling was definitely for the worse.  The new faces give overly strong emphasize to the titles, as compared to the content, and do not mix well with the cursor and the TODO faces.

The input cursor is not aligned to the heading markers anymore, but instead almost appears to be on a different line:

![bildschirmfoto 2013-08-29 um 12 15 52](https://f.cloud.github.com/assets/224922/1048797/0730e5fe-1094-11e3-9a89-e683998cb21f.png)

Letters in a header are also not aligned to the cursor anymore:

![bildschirmfoto 2013-08-29 um 12 22 05](https://f.cloud.github.com/assets/224922/1048853/de4a212c-1094-11e3-8ac7-2196a0819db5.png)

And worst of all, TODO tags are not scaled along with the headers, and thus are almost diminished, especially in high level headers:

![bildschirmfoto 2013-08-29 um 12 22 54](https://f.cloud.github.com/assets/224922/1048881/46170e46-1095-11e3-8030-7e01f2fc986a.png)

Compared to the heading the TODO tag is so small now, that it hardly catches the eye.

I fail to see the rationale behind this change, and cannot but wonder whether anyone ever actually tested it.  I would appreciate, if this theme did not introduce so intrusive faces, at least not without prior notice and some clean way to disable them.

**Comment by imranmunshi** [comment]
I am getting this issue on emacs 25.2.1 on Arch Linux.
solarized-theme from melpa, disable scaling for org mode in solarized using customization, but no effect. Org-mode still displays proportional fonts.
